version: '3.1'
services:
  db:
    image: kartoza/postgis
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql
  covid_services:
    build: .
    command: bash iniciar.sh
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    env_file:
      - covid.env
    depends_on:
      - db
