version: '3.1'

services:
  db:
    image: mdillon/postgis
    ports:
      - "9132:5432"
    env_file:
      - covid.env
  covid_services:
    build: .
    command: bash iniciar.sh
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_HOST=db
    env_file:
      - covid.env
    depends_on:
      - db
