version: '3.1'

services:
  db:
    image: mdillon/postgis
    ports:
      - "9132:5432"
    volumes:
      - covid_data:/var/lib/postgresql/data/
    env_file:
      - .covid.prod.env
  covid_services:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn django_covid.wsgi:application --bind 0.0.0.0:8000 -w 4
    expose:
      - 8000
    environment:
      - POSTGRES_HOST=db
    volumes:
      - covid_static:/code/staticfiles
    env_file:
      - .covid.prod.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - covid_services
    volumes:
      - covid_static:/www/staticfiles

volumes:
  covid_data:
  covid_static:
