version: '3.1'

services:
  db:
    image: mdillon/postgis
    ports:
      - "9132:5432"
    env_file:
      - .covid.prod.env
  covid_services:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash docker/iniciar.prod.sh
    expose:
      - 8000
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .covid.prod.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - covid_services
