version: '3.1'

services:
  db:
    image: mdillon/postgis
    ports:
      - "9312:5432"
  covid_services:
    build: docker/
    command: bash docker/iniciar.sh
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_HOST=db
    env_file:
      - covid.env
    depends_on:
      - db
