version: '3.1'

services:
  db:
    image: mdillon/postgis
    ports:
      - "9132:5432"
    env_file:
      - .covid.prod.env
  covid_services:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn django_covid.wsgi:application -w 4 --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .covid.prod.env
    depends_on:
      - db
